[project]
name = "exercicio-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.6.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
exercicio-1 = "exercicio_1:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
